// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace STI_Entrevista_03_03_2025.DBModels;

public partial class CadastroVeiculo
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Placa { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Marca { get; set; }

    [Required]
    [StringLength(35)]
    [Unicode(false)]
    public string Modelo { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Cor { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Porte { get; set; }

    [Required]
    [Column("Tipo_de_Carga")]
    [StringLength(20)]
    [Unicode(false)]
    public string TipoDeCarga { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Chassis { get; set; }
}